- hosts: all
  become: true
  become_user: downloads
  tasks:
    - name: "Upload signatures"
      copy:
        src: "{{ item.key }}"
        dest: "{{ docroot }}/{{ item.value }}"
      loop: "{{ files|dict2items }}"
