- hosts: all
  become: true
  become_user: downloads
  tasks:
    - name: "Upload signatures"
      copy:
        src: "{{ item.key }}"
        dest: "{{ docroot }}/{{ item.value }}"
      loop: "{{ files|dict2items }}"

    - name: "Invalidate CDN cache"
      command: "fastly-purge https://downloads.theforeman.org {{ item.value }}"
      loop: "{{ files|dict2items }}"
